apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymybuddy-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      db: paymybuddy
  template:
    metadata:
      labels:
        db: paymybuddy
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paymybuddy-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: db_paymybuddy
            - name: MYSQL_USER
              value: paymybuddy_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paymybuddy-secret
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: init-script
          configMap:
             name: initdb-script
---       
apiVersion: v1
kind: Service
metadata:
  name: paymybuddy-db
  namespace: default
spec:
  selector:
    db: paymybuddy
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi