apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymybuddy-backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: paymybuddy
  template:
    metadata:
      labels:
        app: paymybuddy
    spec:
      containers:
        - name: paymybuddy-backend
          image: punkgrb/paymybuddy-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: paymybuddy-configmap
                  key: APP_PORT
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: paymybuddy-configmap
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: paymybuddy-configmap
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paymybuddy-secret
                  key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: paymybuddy-service
  namespace: default
spec:
  selector:
    app: paymybuddy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP