apiVersion: v1
kind: Service
metadata:
  name: paymybuddy-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: paymybuddy
  ports:
    - protocol: TCP
      port: 80        # Public port
      targetPort: 8080 # Port your container listens to
      nodePort: 30007  # Optional: Specify a custom node port (must be in range 30000–32767) # Port your container listens to